### ISSUE TITLE
你好，请问您训练模型需要多长的时间？

### ISSUE THREAD

**Issue by alapan13** [KittenCN/stock_prediction#10]
因为我在训练模型的时候发现耗时很长，需要70小时左右，所以想问问您训练的大概时长是多少。

**Comment by KittenCN** [comment]
全数据的话，这里一个epoch大概需要15小时，我已经跑了40个epoch了

**Comment by alapan13** [comment]
我看了您的20230412发的更新，我停止训练之后，重新预处理数据了，但是在执行predict.py的过程中出现了如下错误：RuntimeError: Error(s) in loading state_dict for TransformerModel:
        size mismatch for embedding.weight: copying a param with shape torch.Size([512, 20]) from checkpoint, the shape in current model is torch.Size([512, 28]).
我在网上搜索的解决方案都解决不了此问题。请问您遇到此问题了吗？如果遇到了，是如何解决的？

**Comment by KittenCN** [comment]
我在readme的new已经写了，这是之前一个bug的修复，之前会导致输入维度少计算8个，现在补上了，但是模型就要重新训练了，如果想使用之前的模型，就去init里面把输入维度改为20，就可以了，但是这样会少计算8个target的维度
