### ISSUE TITLE
tushare现在获取数据都好慢。。用akshare更好，免费，速度也快

### ISSUE THREAD

**Issue by pipivv** [KittenCN/stock_prediction#14]
tushare现在获取数据都好慢。。用akshare更好，免费，速度也快

**Comment by KittenCN** [comment]
tushare免费的有限速，1分钟只能调用50次，全部更新一次要1个多小时，所以慢;
akshare我去研究下看看

**Comment by KittenCN** [comment]
已经增加akshare数据接口,谢谢
