### ISSUE TITLE
Is it possible to get data from other sources?

### ISSUE THREAD

**Issue by danielx5z** [KittenCN/stock_prediction#16]
Hi,

I am outside China and Tushare unfortunately requires Chinese mobile number in order to register. Also, I couldn't understand Akshare and their server is in China which is too slow. I am interested in EU indices(DAX, FTSE etc.). Is it possible to get the training data from other sources for example Yahoo Finance?

Regards

**Comment by KittenCN** [comment]
I have not paid attention to the EU index data interface, give me a little time, I will look and research (such as Yahoo Finance), if you have a suitable api interface, you can also recommend to me, thank you!

**Comment by danielx5z** [comment]
I don't know any api for EU indices at the moment. For EU and US I saw people get their data from Yahoo. Please let me know if you improve someway to add data from Europe and thank you for your interest.

**Comment by danielx5z** [comment]
I would like to add I had some problems with newer version of yfinance module. It doesn't work correctly. I find that downloading csv file directly from Yahoo Finance better option.

On Historical Data tab on Yahoo Finance of the selected stock we can select dates and download the csv.

**Comment by KittenCN** [comment]
> I would like to add I had some problems with newer version of yfinance module. It doesn't work correctly(I get blank returns). I find that downloading csv file directly from Yahoo Finance better option.
> 
> On Historical Data tab on Yahoo Finance of the selected stock we can select dates and download the csv.

I only tested an earlier version of yfinance, the most detailed version is the one with compatibility issues, the version I tested available has been placed in the install_files directory.

**Comment by KittenCN** [comment]
> I don't know any api for EU indices at the moment. For EU and US I saw people get their data from Yahoo. Please let me know if you improve someway to add data from Europe and thank you for your interest.

I have increased the download for the U.S. and European data, the actual training and prediction also need to modify the relevant settings of the init, you can try it yourself, you can also wait a while, I will write the relevant code in, these two days a little busy

**Comment by danielx5z** [comment]
Hello again,

I did install yfinance with the tar.gz file you provided however I got bunch of JSON errors and couldn't get data with it. To give it a try I installed the latest versionyfinance==0.2.18 and with that I was able to download csv's without a problem. Is yfinance-0.1.59 version you provided working fine for you? If it is, that is weird.

With the downloaded csv's I did some test training but I am not satisfied with the results I will have to look into this deeper probably on the weekend.

Thank you for adding yfinance option and your dedication.

Cheers

**Comment by KittenCN** [comment]
yfinance-0.1.59, I haven't tested it, and I don't have time to test it for now, sorry about this...

**Comment by KittenCN** [comment]
I have completed the relevant code and the following steps are required to use Yahoo data:
1. modify the api parameter of getdata.py to yfinance
2. Modify the adjust parameter of getdata.py to fit the content
3. modify the yfi_ticker array in line 272 of getdata.py file and fill it with the ids you need
4. run getdata.py and download all the data (if there is a problem, it is most likely that the IP address is restricted, I can only use VPN to download properly here, I am also looking for a more stable interface)
5. run data_preprocess.py and package it into a PKL serialization file
6. modify the init.py file, comment out the following contents of "## akshare data list", and uncomment the following contents of "## yfinance data list"
7. Modify the api parameter of predict.py to yfinance
8. modify the other parameters in init.py and predict.py as appropriate
9. run predict.py for training
