### ISSUE TITLE
预测目标是价格，但用MAPE做评价？

### ISSUE THREAD

**Issue by windblood** [KittenCN/stock_prediction#21]
不建议直接预测价格，如果预测价格，MAPE不是合适指标，或者认为有效的指标阈值必须低于平均每日涨跌幅
比如0.04的MAPE，是不是意味着预测价格相对实际价格误差达到4%？但股票隔夜跳空涨跌幅绝对值均值都不超过1%

**Comment by KittenCN** [comment]
很有道理，我只是个做神经网络的软件工程师，对于股票等金融概念完全不懂，烦请赐教，不胜感激
