### ISSUE TITLE
刚配置好环境训练耗时要60个小时

### ISSUE THREAD

**Issue by eru1030** [KittenCN/stock_prediction#26]
大佬，我用笔记本配置好了，我开始训练transformer，300万条数据要62小时。怕电脑挂掉就暂时放弃了。有没有训练好的模型分享啊？

**Comment by KittenCN** [comment]
62小时是1个epoch，正常要跑上几十上百个才行。神经网络训练个几百小时很正常的。。

**Comment by eru1030** [comment]
今天花了6个小时训练了一遍LSTM，加一个小时test完毕。最后我开始predict。发现生成的图片close对应原数据的high

**Comment by KittenCN** [comment]
> 今天花了6个小时训练了一遍LSTM，加一个小时test完毕。最后我开始predict。发现生成的图片close对应原数据的high

标准LSTM的话，1个epoch应该是不够。。我在写一个基于CNN的LSTM，可能有助于缩短训练时间

**Comment by mingxing0769** [comment]
@KittenCN 可以间隔训练？如先训练10 个epoch  再有时间后再训练 10 个epoch?  只对200只股票数据 训练10个epoch 都得20个小时

**Comment by KittenCN** [comment]
> @KittenCN 可以间隔训练？如先训练10 个epoch 再有时间后再训练 10 个epoch? 只对200只股票数据 训练10个epoch 都得20个小时
当然可以啊，默认就是会去找有没有已经训练了的模型文件，然后自动判断继续训练还是新训练

**Comment by mingxing0769** [comment]
@KittenCN 
![GenericData_TRANSFORMER_20230606222018_train_loss](https://github.com/KittenCN/stock_prediction/assets/124433897/7b7694bd-532c-4b87-9b80-e915e8092981)
如前面所说  200股票 第八次训练的结果   看样子还得花不少时间了
