### ISSUE TITLE
请问这个模型最多可以预测多少天啊？

### ISSUE THREAD

**Issue by guofanshun123456** [KittenCN/stock_prediction#28]

**Comment by KittenCN** [comment]
理论上没有上限啊，只要给合理的窗口时间进行训练就行。实际嘛，预测时间越长，累计误差越大

**Comment by guofanshun123456** [comment]
> 理论上没有上限啊，只要给合理的窗口时间进行训练就行。实际嘛，预测时间越长，累计误差越大

训练出的模型测试曲线与实际情况很接近，但预测结果出现断崖式的偏高，想请教一下大佬是什么原因啊？
![下载](https://github.com/KittenCN/stock_prediction/assets/132997256/b76c6464-9572-4f11-bf1d-dc6c98d1ee43)

![下载 (1)](https://github.com/KittenCN/stock_prediction/assets/132997256/aa0a915f-7148-4829-ac85-db47adf0aee2)
