### ISSUE TITLE
项目建议

### ISSUE THREAD

**Issue by lancewliang** [KittenCN/stock_prediction#30]
https://github.com/lancewliang/stockpredictionai#arimafeature
这是一个老兄很久以前写的系统设计。有些算法我也都是在billbi上学习。也就最近几个月找到了李宏毅的课程，开始认真学习。
我不是专门做算法方向的工程师，最近在学习机器学习，所以能看懂部分了。还是有很多东西不太懂。
你可以借鉴一下他的思路。离实战或许还很遥远。
我也最近在学习你彩票的代码实现，pytorch那个版本你没有实现完我也就暂时不看了。
这个东西就是和炼丹没什么区别，不敢花时间真的下去尝试，只能看这种知识先储备起来，做机器学习工程师真好，就是炼丹有点枯燥还费钱。等失业了再来折腾。期待你的股票仓库能够坚持做下去。

靠数据来预测股票价格我觉得从理论上是有瑕疵的，和随机漫步理论是冲突的。大数据也好学习也好，学习的是有规律的东西。但是股票类似波，是概率而非规律。
如果从选股的角度可能又是有机会的，这样很可能选择到垃圾股，并且依然需要靠人工来进行消息和基本面的判断，那选股的意义或许就没有这么大了。

我之前试想过一个思路，就是不同的ai和那些分析师的预测结果作为特征来高纬度再训练一次，这样相当于做多层数据的训练。就像普通人炒股就是听了不同专家的话，根据专家分析的胜率调整听某个专家的权重，不同ai算法当成一个专家。这样很多专家变成了一个投票集合然后博弈出最后的决定。每天投票一次。
随便写写。

**Comment by KittenCN** [comment]
拜读您的建议，很有意义，彩票预测的项目是我魔改了别人的想法，股票预测是我们公司项目的极简化版，由于最近实在繁忙，都来不及更新，其实就像您说的，纯粹的机器学习是很难完成这两个项目的，特别是彩票这种完全随机事件，当然如果从其他角度考虑，其实还是可以完成一定程度的计算的，这里我不能展开说，这个已经接近与我们公司内部的项目了。总体而言。我也只是抛砖引玉，期望能有更多的朋友参与思考和开发。再次感谢。

**Comment by lancewliang** [comment]
如果方便联系的话把你的联系方式放给我，我的邮箱78599194@qq.com。我和可能这几年会转行，转主观交易i方向。我想在我做工程师最后的时间段，再探索一下这个方向的可能性。如果真的完全没有机缘，将来就彻底投向主观交易了。
